name: devcontainer

services:
    sandbox:
        image: sandbox
        hostname: ubuntu
        container_name: sandbox
        stdin_open: true
        tty: true
        volumes:
            - type: bind
              source: ..
              target: /root/sandbox
